assets:
  twine_token: yegor256/home#assets/aibolit/twine_token
install: |
  export LC_ALL=en_US.UTF-8
  python3 -m pip install --upgrade pip
  python3 -m pip install twine
merge:
  script: |
    make
deploy:
  script: |
    echo There is nothing to deploy
    exit 1
release:
  script: |-
    sed -i "s/0\.0\.0/${tag}/g" aibolit/__init__.py
    git add aibolit/__init__.py
    git commit -am "${tag}"
    python3 --version
    python3 -m pip --version
    make
    python3 setup.py sdist bdist_wheel
    python3 -m twine upload dist/* -u __token__ -p $(cat ../twine_token)
