assets:
  twine_token: yegor256/home#assets/aibolit/twine_token
install: |
  export LC_ALL=en_US.UTF-8
merge:
  script: |
    ./build.sh
deploy:
  script: |
    echo There is nothing to deploy
    exit 1
release:
  script: |-
    sed -i "s/0\.0\.0/${tag}/g" aibolit/__init__.py
    git add aibolit/__init__.py
    git commit -am "${tag}"
    pip3 install --upgrade pip
    pip3 install twine
    ./build.sh
    python3 setup.py sdist bdist_wheel
    python3 -m twine upload dist/* -u __token__ -p $(cat ../twine_token)
