# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT

language: python
sudo: false
install:
  - gem install xcop
  - pip install codecov
script:
  - make
after_success:
  - codecov
