version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
environment:
  matrix:
    - python: "py37"
install:
- set PATH=C:\Python37;C:\Python37\Scripts;%PATH%
- python -m pip install --upgrade pip
- pip install aibolit
test_script:
- aibolit
