version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
environment:
  matrix:
    - python: "py37"
install:
- python --version
- set PATH=C:\Python37;C:\Python37\Scripts;%PATH%
- python -m pip install --upgrade pip
- pip install torch==1.4.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
- pip install aibolit
test_script:
- aibolit
