version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
install:
- set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
- python --version

build_script:
- cd C:\projects\aibolit
- pip install .

test_script:
- aibolit --version

