version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages

image: Previous Visual Studio 2019
install:
- set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;C:\Python37-x64\Library\bin;%PATH%
- python --version
build_script:
- cd C:\projects\aibolit
- pip install .

test_script:
- aibolit --version

