version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
#environment:
#  matrix:
#    - python: "py37"
install:
- set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
- python --version
- python -m pip install --upgrade pip
#- pip install torch==1.4.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
build_script:
- pip install aibolit

test_script:
- aibolit --version

